#!/usr/bin/env bash
#scripts to install NGINX server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
