#!/usr/bin/env bash
#script that displays numbers from 1 to 100.
for n in {1..100}
do
    if [ $((n % 15)) == 0 ]
    then
	echo "FizzBuzz"
    elif [ $((n % 3)) == 0 ]
    then
	echo "Fizz"
    elif [ $((n % 5)) == 0 ]
    then
	echo "Buzz"
    else
	echo "$n"
    fi
done
