#!/usr/bin/env bash
# displays bad luck for 4th iteration and good luck for 8th, "Holberton School" for others
n=1
while [ $n -le 10 ]
do
    if [ $n == 4 ]
    then
	echo "bad luck"
    elif [ $n == 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let n++
done
