#!/usr/bin/env bash
# displays number from 1-20 and displays bad luck for 4th, 9th, and 17th iteration.
n=1
while [ $n -le 20 ]
do
    echo "$n"
    case "$n" in
	4 )
	echo "bad luck from China";;
	9 )
	echo "bad luck from Japan";;
	17 )
	echo "bad luck from Italy";;
    esac
    let n++
done
